require("elvis.semi")
--require "elvis.icons"
require "elvis.options"
require "elvis.keymaps"
require "elvis.plugins"
require "elvis.colorscheme"
require "elvis.cmp"
require "elvis.lsp"
require "elvis.telescope"
require "elvis.gitsigns"
require "elvis.treesitter"
require "elvis.autopairs"
require "elvis.comment"
require "elvis.nvim-tree"
require "elvis.bufferline"
require "elvis.lualine"
require "elvis.toggleterm"
require "elvis.project"
require "elvis.impatient"
require "elvis.indentline"
require "elvis.alpha"
require "elvis.whichkey"
require "elvis.autocommands"



